name: share_bridge_core
description: Core Dart models, share content types, result codes, provider contracts, and dispatcher for modular social sharing plugins.
version: 0.1.0-dev.4
homepage: https://github.com/JamesGZM/flutter_share_bridge
repository: https://github.com/JamesGZM/flutter_share_bridge/tree/master/packages/share_bridge_core
issue_tracker: https://github.com/JamesGZM/flutter_share_bridge/issues
topics:
  - share
  - social-sharing
  - dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
