name: share_bridge_qq
description: QQ and QZone sharing plugin for Share Bridge.
version: 0.1.0-dev.2
homepage: https://github.com/JamesGZM/flutter_share_bridge
repository: https://github.com/JamesGZM/flutter_share_bridge/tree/master/packages/share_bridge_qq
issue_tracker: https://github.com/JamesGZM/flutter_share_bridge/issues
topics:
  - flutter
  - share
  - qq
  - social-sharing
platforms:
  android:
  ios:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  share_bridge_core: ^0.1.0-dev.1
  share_bridge_qq_android: ^0.1.0-dev.1
  share_bridge_qq_ios: ^0.1.0-dev.1
  share_bridge_qq_ohos: ^0.1.0-dev.1
  share_bridge_platform_interface: ^0.1.0-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  plugin_platform_interface: ^2.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        default_package: share_bridge_qq_android
      ios:
        default_package: share_bridge_qq_ios
      ohos:
        default_package: share_bridge_qq_ohos
