name: share_bridge_wechat_ohos
description: HarmonyOS federated implementation of share_bridge_wechat using the Tencent WeChat OpenSDK for OHOS.
version: 0.1.0-dev.4
homepage: https://github.com/JamesGZM/flutter_share_bridge
repository: https://github.com/JamesGZM/flutter_share_bridge/tree/master/packages/share_bridge_wechat_ohos
issue_tracker: https://github.com/JamesGZM/flutter_share_bridge/issues
topics:
  - flutter
  - share
  - wechat
  - harmonyos

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  share_bridge_platform_interface: ^0.1.0-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: share_bridge_wechat
    platforms:
      ohos:
        package: com.gongziming.share_bridge_wechat
        pluginClass: ShareBridgeWechatPlugin
        dartPluginClass: ShareBridgeWechatOhos
