name: share_bridge_qq_ohos
description: HarmonyOS implementation of share_bridge_qq.
version: 0.1.0-dev.1
repository: https://github.com/JamesGZM/flutter_share_bridge

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  share_bridge_platform_interface: ^0.1.0-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    implements: share_bridge_qq
    platforms:
      ohos:
        package: com.gongziming.share_bridge_qq
        pluginClass: ShareBridgeQqPlugin
        dartPluginClass: ShareBridgeQqOhos
